#!/usr/bin/python
# -*- coding: utf-8 -*-

a = 65
print type(a)
#http://www.cplusplus.com/reference/cstdio/printf/?kw=printf
print "Mainiga a vertiba ka dec skaitlis ir %d"%(a)
print "Mainiga a vertiba ka hex skaitlis ir %x"%(a)
print "Mainiga a vertiba ka oct skaitlis ir %o"%(a)
print "Mainiga a vertiba ka simbols skaitlis ir %c"%(a)

a = 'A'
print type(a)
print "Mainiga a vertiba ka dec skaitlis ir %d"%(ord(a))
print "Mainiga a vertiba ka hex skaitlis ir %x"%(ord(a))
print "Mainiga a vertiba ka oct skaitlis ir %o"%(ord(a))
print "Mainiga a vertiba ka simbols ir %c"%(a)

a = '\n'
print type(a)
print "Mainiga a vertiba ka dec skaitlis ir %d"%(ord(a))
print "Mainiga a vertiba ka hex skaitlis ir %x"%(ord(a))
print "Mainiga a vertiba ka oct skaitlis ir %o"%(ord(a))
print "Mainiga a vertiba ka simbols ir %c"%(a)
a = 8.5
print type(a)
print "Mainiga a vertiba ka dec skaitlis ir %d"%(a)
print "Mainiga a vertiba ka hex skaitlis ir %x"%(a)
print "Mainiga a vertiba ka oct skaitlis ir %o"%(a)
print "Mainiga a vertiba ka simbols ir %c"%(a)

